$schema: "http://json-schema.org/draft-07/schema#"

type: "array"
items:
  $ref: "#/definitions/object_with_date_or_datetime"

definitions:
  date:
    description: "Y-m-d"
    type: "string"
    pattern: "^\\d{4}-\\d{2}-\\d{2}$"
  datetime:
    description: "Y-m-d H:i:s"
    type: "string"
    pattern: "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$"
  object_with_date_or_datetime:
    properties:
      birthday:
        $ref: "#/definitions/date"
    patternProperties:
      ^[a-z_]*_at$:
        anyOf:
          - $ref: "#/definitions/date"
          - $ref: "#/definitions/datetime"
